name: Makefile CI

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update \
            && sudo apt-get -y install build-essential nasm genisoimage \
            && sudo apt-get clean

      - name: make ISO
        run: make os.iso
